SOF-116 Section overview
Project-Accessibility/app pull request #13
Opened 2022-04-04 14:23 UTC by GewoonJaap

## Description

Added the SectionList component which displays a list of buttons.

## Review focus
Check if everything is as expected
## Checklist

- [x] I have run `yarn format`
- [x] I have run `yarn eslint` and fixed any issues
- [x] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

![afbeelding](https://user-images.githubusercontent.com/33700526/161564837-961df762-fdd9-4dc5-8f64-bd599ed422f6.png)
![afbeelding](https://user-images.githubusercontent.com/33700526/161564881-29a4302b-6ca4-41d9-9345-9c43a38f9e17.png)
![afbeelding](https://user-images.githubusercontent.com/33700526/161564926-dfd6927f-a7a5-4f2f-9078-86e5e68d8682.png)

</details>

2022-04-04 19:47 UTC, wwessel01 requested changes
De styling komt nog niet helemaal overeen met het wireframe. De 'alle onderdelen' lijst moet ook eigenlijk uitklapbaar kunnen zijn bijvoorbeeld. Zou je hier nog naar kunnen kijken?

2022-04-05 14:26 UTC, GewoonJaap commented
> De styling komt nog niet helemaal overeen met het wireframe. De 'alle onderdelen' lijst moet ook eigenlijk uitklapbaar kunnen zijn bijvoorbeeld. Zou je hier nog naar kunnen kijken?

![afbeelding](https://user-images.githubusercontent.com/33700526/161776516-cf24b707-ec48-4e06-8874-e0d172cd0004.png)
![afbeelding](https://user-images.githubusercontent.com/33700526/161776539-d65adaf3-1152-4be5-a6e0-274290d796d6.png)
Zit er nu in :)

2022-04-05 19:36 UTC, wwessel01 approved these changes

2022-04-05 20:32 UTC, IntissarJ approved these changes

2022-04-05 20:32 UTC, merged