Feature/sof 316 logo
Project-Accessibility/app pull request #24
Opened 2022-04-26 02:38 UTC by IntissarJ

**Closes #XX**

## Description

Dit is voor de app icon en app naam voor in de app stor, play store en tel display.

## Review focus

kleine pr voor alleen foto en benaming, met groep verband bespreken of benaming goed is samen met veron.

## Checklist

- [ ] I have run `yarn format`
- [ ] I have run `yarn eslint` and fixed any issues
- [ ] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/45880258/165208438-c75ba1be-c386-4f51-941b-5c3ef94da42b.png)

</details>

2022-04-26 06:11 UTC, GewoonJaap requested changes

2022-04-26 06:11 UTC, GewoonJaap commented on ios/ProjectAccessibility/Info.plist
> -	<string>ProjectAccessibility</string>
Typo

2022-04-26 06:11 UTC, GewoonJaap commented on android/app/src/main/res/values/strings.xml
> -    <string name="app_name">ProjectAccessibility</string>
Typo

2022-04-26 08:02 UTC, GewoonJaap approved these changes

2022-04-28 15:09 UTC, milovdpas approved these changes

2022-04-28 19:48 UTC, merged