feature/SOF-75 nearby sections
Project-Accessibility/app pull request #29
Opened 2022-05-10 18:54 UTC by milovdpas

**Closes #75**

## Description

Dichtsbijzijnde onderdelen implementatie.

## Review focus

Kijk of de alles goed gestructureerd is en of de naamgeving goed is. Check of geofence werkt.

## Checklist

- [ ] Geofence aanmaken in het dashboard
- [ ] In de extended controls van je emulator de locatie van je telefoon in de geofence zetten.
- [ ] Vervolgens in de app toestemming geven tot de locatie
- [ ] Check of het onderdeel wordt getoond in de "dichtsbijzijnde onderdelen"

## Screenshots or videos

![image](https://user-images.githubusercontent.com/63716517/167701740-6dfd5bbe-086d-4d3b-af0a-3143551a7e26.png)

2022-05-12 10:42 UTC, MartijnAmbagtsheer requested changes

2022-05-12 10:42 UTC, MartijnAmbagtsheer commented on src/data/location/Radar.ts
> +    console.log('run radar tracking');
Wat is hier de meerwaarde van?

2022-05-12 10:42 UTC, MartijnAmbagtsheer commented on src/data/location/Radar.ts
> +    console.log('trigger');
Wat is hier het nut van?

2022-05-15 09:11 UTC, GewoonJaap approved these changes

2022-05-16 19:01 UTC, MartijnAmbagtsheer approved these changes

2022-05-16 19:06 UTC, merged