SOF-148-beantwoorden-open-vraag MVP
Project-Accessibility/app pull request #32
Opened 2022-05-15 20:51 UTC by Darkshadenl

**Closes #XX**

## Description

- Open question type added (OpenQuestion.txt)
- Added (or edited, don't remember) QuestionList.tsx to see if questions been answered
- edited mockobject.json. questionoptions -> answers -> answer is now an array. Reflected in models
- edited questionscreen to support openquestion and future questiontypes. can be improved further upon.
- When sectionscreen comes into view, data gets (theoretically) send to the api. This is done from the TempStorage.tsx
- Tempstorage.tsx: uses Asyncstorage to provide local storage functionality. Is in a MVP stage. Upload to API not implemented. Local storage works and can be used. Openquestion screen temp contains a 'clear local storage' button, until getting new data from API auto clears it. 

## Review focus

This is an MVP. Due to a lot of disconnect between the branches it's smart to just merge this in, and merge the rest in (talking about the API upload/download implementation in the app). Stuff that misses or is not yet implemented right now can be easily implemented after the merge. 

Focus should be on code quality and if it's future proof. 

## Checklist

- [x] I have run `yarn format`
- [x] I have run `yarn eslint` and fixed any issues
- [x] This PR does not add any errors to the console -> there is an error but it's not mine. I guess it's because I don't have a docker container with api running?

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

</details>

2022-05-19 09:28 UTC, wwessel01 requested changes
We kunnen beter de opslaan knop als apart component maken. Dan kunnen we de antwoord data meegeven aan het opslaan component en deze handelt het vervolgens allemaal af. In QuestionScreen kunnen we dan dit component gebruiken als opslaan knop

2022-05-20 06:53 UTC, wwessel01 approved these changes, later dismissed

2022-05-20 10:27 UTC, GewoonJaap approved these changes

2022-05-20 10:57 UTC, milovdpas approved these changes

2022-05-20 10:58 UTC, merged