add new implementation of Answer and add RangeSlider to question screen
Project-Accessibility/app pull request #38
Opened 2022-05-20 18:33 UTC by milovdpas

**Closes #151**

add new implementation of Answer and add RangeSlider to question screen

2022-05-22 08:35 UTC, GewoonJaap approved these changes

2022-05-22 15:02 UTC, Darkshadenl requested changes
Ik krijg allerlei errors. Yarn install gedaan. Idk. 
9 errors (meeste promise dingen maar dat zal wel). 
![image](https://user-images.githubusercontent.com/26344464/169701793-0c2e8484-9b99-4ee7-9d78-1e3108655a13.png)
![image](https://user-images.githubusercontent.com/26344464/169701801-41277149-db6d-4c0e-b224-4504b3e39c6d.png)

2022-05-22 15:05 UTC, GewoonJaap commented
> Ik krijg allerlei errors. Yarn install gedaan. Idk. 9 errors (meeste promise dingen maar dat zal wel). ![image](https://user-images.githubusercontent.com/26344464/169701793-0c2e8484-9b99-4ee7-9d78-1e3108655a13.png) ![image](https://user-images.githubusercontent.com/26344464/169701801-41277149-db6d-4c0e-b224-4504b3e39c6d.png)

Heb je wel een questionoption die een range heeft meegegeven?

2022-05-24 08:56 UTC, IntissarJ requested changes

2022-05-24 08:56 UTC, IntissarJ commented on src/components/question/QuestionList.tsx
> +    if (questionOption.answer.values.length > 0) {
Nu is het zo wanneer ik bij questionlist terecht kom dat beantwoord op 0/2 staat terwijl er wel vinkjes staan voor elk vraag titel.

2022-05-24 10:44 UTC, Darkshadenl approved these changes

2022-05-25 16:17 UTC, IntissarJ approved these changes

2022-05-25 16:17 UTC, merged