Accessibility additions
Project-Accessibility/app pull request #40
Opened 2022-05-24 11:31 UTC by Darkshadenl

**Closes #XX**

## Description

Just a few lines of accessibility hints in different places.

## Review focus

## Checklist

- [ ] I have run `yarn format`
- [ ] I have run `yarn eslint` and fixed any issues
- [ ] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

</details>

2022-05-24 17:53 UTC, GewoonJaap approved these changes

2022-05-24 18:15 UTC, MartijnAmbagtsheer requested changes
Iets meer consistentie inbouwen.

2022-05-24 18:15 UTC, MartijnAmbagtsheer commented on src/components/questions/AudioRecorder.tsx
> +              accessibilityLabel={'Stop opname knop'}
"Spraakopname stoppen". Dat het een knop is hoor je aan het geluidje en wordt ook voorgelezen (op Android iig)

2022-05-24 18:15 UTC, MartijnAmbagtsheer commented on src/components/questions/AudioRecorder.tsx
> +              accessibilityHint={'Spreek uw antwoord in na het activeren van de knop'}
"Start spraakopname"

2022-05-24 18:15 UTC, MartijnAmbagtsheer commented on src/components/questions/AudioRecorder.tsx
> +              accessibilityLabel={'Pauzeer knop'}
"pauzeer spraakopname"

2022-05-24 18:15 UTC, MartijnAmbagtsheer commented on src/components/questions/AudioRecorder.tsx
> +              accessibilityLabel={'Afspeel knop'}
"Spraakopname afspelen"

2022-05-24 18:15 UTC, MartijnAmbagtsheer commented on src/components/questions/AudioRecorder.tsx
> +            accessibilityHint={'Verwijderd opname'}
"Verwijder spraakopname"

2022-05-24 18:15 UTC, MartijnAmbagtsheer commented on src/components/questions/AudioRecorder.tsx
> +            accessibilityHint={'Ga terug naar begin opname'}
"Spraakopname starten vanaf het begin"

2022-05-24 18:15 UTC, MartijnAmbagtsheer commented on src/screens/SectionScreen.tsx
> +              } beantwoord.`}
"van de ... vragen beantwoord"

2022-05-25 19:53 UTC, MartijnAmbagtsheer approved these changes

2022-05-25 19:53 UTC, merged