SOF-335 Video component
Project-Accessibility/app pull request #46
Opened 2022-05-30 10:06 UTC by wwessel01

2022-05-30 23:13 UTC, milovdpas requested changes
Op de 2 kleine comments na, werkt alles in de app goed.

2022-05-30 23:13 UTC, milovdpas commented on src/components/questions/VideoSelector.tsx
> +  //Check if video already exists (this is when image is already uplaoded to DB), if so, set correct metadata
Spelfout: plaoded

2022-05-30 23:13 UTC, milovdpas commented on src/components/questions/VideoSelector.tsx
> +      console.log('Permissie afgewezen');
logs in het engels

2022-06-02 17:04 UTC, MartijnAmbagtsheer requested changes

2022-06-02 17:04 UTC, MartijnAmbagtsheer commented on src/components/questions/VideoSelector.tsx
> +  const [fullScreen, setFullScreen] = React.useState(false);
Ik zag het bij de demo ook al. Ik heb liever dat het dan ook daadwerkelijk full screen wordt en niet gewoon vergroot op de pagina. Dus net zoals met YouTube ofzo gewoon een 'laag' over het scherm met daarin de video waarbij hij past in het scherm.

2022-06-03 16:35 UTC, GewoonJaap approved these changes

2022-06-03 18:48 UTC, milovdpas approved these changes

2022-06-03 18:54 UTC, MartijnAmbagtsheer commented
Nog NIET mergen!!

2022-06-03 18:54 UTC, MartijnAmbagtsheer requested changes
Fix met alignment

2022-06-04 09:42 UTC, MartijnAmbagtsheer approved these changes

2022-06-04 09:42 UTC, merged