SOF-405 apple store
Project-Accessibility/app pull request #50
Opened 2022-06-01 11:45 UTC by GewoonJaap

**Closes #XX**

## Description

## Review focus

## Checklist

- [ ] I have run `yarn format`
- [ ] I have run `yarn eslint` and fixed any issues
- [ ] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

</details>

2022-06-03 09:23 UTC, wwessel01 approved these changes

2022-06-03 12:30 UTC, MartijnAmbagtsheer requested changes

2022-06-03 12:30 UTC, MartijnAmbagtsheer commented on ios/ProjectAccessibility/Info.plist
> +	<string>$(PRODUCT_NAME) wilt graag locatie gebruiken voor locatiebepaling.</string>
Graag overal hetzelfde als op regel 59

2022-06-09 09:24 UTC, GewoonJaap commented on ios/ProjectAccessibility/Info.plist
> +	<string>$(PRODUCT_NAME) wilt graag locatie gebruiken voor locatiebepaling.</string>
Aangepast

2022-06-15 07:36 UTC, MartijnAmbagtsheer approved these changes

2022-06-15 08:19 UTC, merged