added circuit breaker to Queue.ts
Project-Accessibility/app pull request #58
Opened 2022-06-03 09:39 UTC by milovdpas

## Description

De queue blijft re-tryen, terwijl er 9/10x een error terug komt als er bijv iets niet goed is met een antwoord.

2022-06-03 09:49 UTC, GewoonJaap requested changes, later dismissed
- Elk queueObject een variabele `tries` geven, als die dan boven 4 ofzo komt, uit de queue halen
- Voordat de queue start, kijken of de portal online is. GET /api/ping voor gebruiken. Moet nog even een API endpoint functie voorgeschreven worden

2022-06-03 12:15 UTC, MartijnAmbagtsheer requested changes

2022-06-03 12:15 UTC, MartijnAmbagtsheer commented on src/data/localStorage/Queue.ts
> +  errorThreshold: number; // When errorThreshold:number requests fail, trip the circuit resetTimeout:number
Ik zou dit niet met een timer doen. 2x proberen en bijv elke minuut even een ping doet naar de webportal. Als die een goede response krijgt dan weer 2x proberen.

2022-06-03 17:32 UTC, milovdpas commented on src/data/localStorage/Queue.ts
> +  errorThreshold: number; // When errorThreshold:number requests fail, trip the circuit resetTimeout:number
Yes dit was besproken op school, Wessel ging hier mee verder.

2022-08-29 18:05 UTC, MartijnAmbagtsheer approved these changes
Voorlopig voldoende. Geen prioriteit nu

2022-08-29 18:14 UTC, merged