SOF-119 Onderdeel details
Project-Accessibility/app pull request #6
Opened 2022-03-31 08:20 UTC by IntissarJ

---
title: 'SOF-XXX Description'
labels: enhancement
assignees: ''
---

**Closes #XX**

## Description

Onderdeel details view waar nog gekeken naar moet worden voor database gegevens voor onderdeel titel en onderdeel beschrijving. 

## Review focus

Vooral controleren of de view volgens wireframes klopt en of het voldoet aan de toegankeliijksheid op AAA niveu

## Checklist

- [ ] I have run `yarn format`
- [ ] I have run `yarn eslint` and fixed any issues
- [ ] This PR does not add any errors to the console

A build will automatically be run by GitHub actions when any changes are made on this PR. This must complete successfully before merging.

## Screenshots or videos

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/45880258/161009394-6df06b9f-4284-4edb-9fc8-428d19382b8c.png)

</details>

2022-03-31 08:44 UTC, GewoonJaap requested changes

2022-03-31 08:44 UTC, GewoonJaap commented on App.tsx
> +  //const isDarkMode = false;
Kan dit niet weg als het uitgecomment is?

2022-03-31 08:47 UTC, GewoonJaap approved these changes

2022-03-31 19:28 UTC, wwessel01 commented on src/screens/SectionScreen.tsx
> +    color: 'black',
Hier even `color: COLORS.black` van maken, dan houden we alle kleuren lekker consistent bij elkaar

2022-03-31 19:29 UTC, wwessel01 requested changes
Even de color aanpassen, voor de rest is dit voor nu goed. Later gaan we nog wel de components hierin verwerken

2022-04-03 09:13 UTC, wwessel01 approved these changes
Toppie

2022-04-03 09:13 UTC, merged